# Generated by Django 3.2 on 2023-02-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
