# Generated by Django 3.2 on 2023-02-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
