# Generated by Django 3.2 on 2023-03-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='offer_type',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Full-time', 'Full-time'), ('Intern + Full-time', 'Intern + Full-time')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='package',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='placed_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='year_of_passing',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
