# Generated by Django 3.2 on 2023-03-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_auto_20230329_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Eg. Aptitude, Technical, HR, etc. (must be unique)', max_length=100, unique=True, verbose_name='Placement Round Name')),
            ],
            options={
                'verbose_name_plural': 'Placement Rounds',
            },
        ),
        migrations.CreateModel(
            name='RoundQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, unique=True, verbose_name='Question')),
                ('placement_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.placementround')),
            ],
            options={
                'verbose_name_plural': 'Round Questions',
            },
        ),
    ]
