# Generated by Django 3.2 on 2023-03-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_placementround_roundquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundquestions',
            name='question',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Question'),
        ),
    ]
