# Generated by Django 3.2 on 2023-03-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_alter_roundquestions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundquestions',
            name='question',
            field=models.TextField(help_text='Enter the question here'),
        ),
    ]
