# Generated by Django 3.2 on 2023-04-04 12:07

from django.db import migrations, models
import django.db.models.deletion
import dynamic_forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_alter_roundquestions_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('form', dynamic_forms.models.FormField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', dynamic_forms.models.ResponseField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.survey')),
            ],
        ),
    ]
