# Generated by Django 4.2 on 2023-04-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_surveyresponse_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundquestions',
            name='placement_round',
        ),
        migrations.AlterField(
            model_name='survey',
            name='topic',
            field=models.CharField(help_text='Eg. Aptitude, Technical, HR, etc. (must be unique)', max_length=100, verbose_name='Placement Round Name'),
        ),
        migrations.DeleteModel(
            name='PlacementRound',
        ),
        migrations.DeleteModel(
            name='RoundQuestions',
        ),
    ]
