# Generated by Django 4.2 on 2023-04-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placement", "0008_remove_roundquestions_placement_round_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="pics/%y/%m/%d/"),
        ),
    ]
