# Generated by Django 4.2 on 2023-04-17 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("placement", "0009_users_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
