# Generated by Django 4.2 on 2023-04-17 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("placement", "0010_surveyresponse_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyresponse",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
